# Generated by Django 3.0.3 on 2020-02-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_teamid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamID',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamID',
            new_name='team',
        ),
    ]
