# Generated by Django 3.0.3 on 2020-02-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_auto_20200228_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
