# Generated by Django 3.0.3 on 2020-02-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamPW',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
