# Generated by Django 3.0.3 on 2020-03-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
