# Generated by Django 3.0.3 on 2020-03-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_auto_20200310_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='requestMade',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
