# Generated by Django 3.0.3 on 2020-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0010_auto_20200310_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isStaff',
            field=models.IntegerField(default=0),
        ),
    ]
