# Generated by Django 3.0.3 on 2020-03-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0011_team_isstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=100)),
                ('projectName', models.CharField(max_length=100, null=True)),
                ('pType', models.CharField(max_length=100, null=True)),
                ('repEmail', models.EmailField(max_length=254, null=True)),
                ('pLength', models.FloatField(null=True)),
                ('pWidth', models.FloatField(null=True)),
                ('pHeight', models.FloatField(null=True)),
                ('sLength', models.FloatField(null=True)),
                ('sWidth', models.FloatField(null=True)),
                ('sHeight', models.FloatField(null=True)),
                ('numPP', models.IntegerField(null=True)),
                ('numBigPed', models.IntegerField(null=True)),
                ('numSmallPed', models.IntegerField(null=True)),
                ('pedReason', models.CharField(max_length=500, null=True)),
                ('numMonitor', models.IntegerField(null=True)),
                ('numTV', models.IntegerField(null=True)),
                ('numTable', models.IntegerField(null=True)),
                ('numChair', models.IntegerField(null=True)),
                ('numHDMI', models.IntegerField(null=True)),
                ('other', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
