# Generated by Django 3.0.3 on 2020-03-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0012_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='numBigPed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='numChair',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='numHDMI',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='numMonitor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='numPP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='numSmallPed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='numTV',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='numTable',
            field=models.FloatField(null=True),
        ),
    ]
