# Generated by Django 3.0.3 on 2020-03-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0013_auto_20200323_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='pedReason',
            new_name='pedDesc',
        ),
    ]
