# Generated by Django 3.0.3 on 2020-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0014_auto_20200323_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reqDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
