# Generated by Django 3.0.5 on 2020-04-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0015_request_reqdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
