# Generated by Django 3.0.5 on 2020-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0016_request_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='yearOfGrad',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='team',
            name='yearOfGrad',
            field=models.IntegerField(default=2020),
        ),
    ]
