# Generated by Django 3.0.3 on 2020-03-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(max_length=100)),
                ('adminPW', models.CharField(default='password', max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
