# Generated by Django 3.0.3 on 2020-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_admin_isstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=100)),
                ('yearOfGrad', models.IntegerField(default=2020, max_length=4)),
                ('projectName', models.CharField(max_length=100, null=True)),
                ('pType', models.CharField(max_length=100, null=True)),
                ('repEmail', models.EmailField(max_length=254, null=True)),
                ('pLength', models.FloatField(null=True)),
                ('pWidth', models.FloatField(null=True)),
                ('pHeight', models.FloatField(null=True)),
                ('sLength', models.FloatField(null=True)),
                ('sWidth', models.FloatField(null=True)),
                ('sHeight', models.FloatField(null=True)),
                ('numPP', models.FloatField(null=True)),
                ('numBigPed', models.FloatField(null=True)),
                ('numSmallPed', models.FloatField(null=True)),
                ('pedDesc', models.CharField(max_length=500, null=True)),
                ('numMonitor', models.FloatField(null=True)),
                ('numTV', models.FloatField(null=True)),
                ('numTable', models.FloatField(null=True)),
                ('numChair', models.FloatField(null=True)),
                ('numHDMI', models.FloatField(null=True)),
                ('other', models.CharField(max_length=500, null=True)),
                ('reqDateTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('uploadedFile', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
