# Generated by Django 3.0.3 on 2020-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_reqdata_uploadedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqdata',
            name='yearOfGrad',
            field=models.IntegerField(default=2020),
        ),
    ]
