# Generated by Django 3.0.3 on 2020-03-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_auto_20200327_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='yearOfGrad',
            field=models.IntegerField(default=2020),
        ),
    ]
