# Generated by Django 3.0.5 on 2020-04-06 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_uploadedfiles_yearofgrad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocateDT', models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 31, 10, 865730))),
                ('allocation', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocateDT', models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 31, 10, 866496))),
                ('clusterID', models.CharField(max_length=100)),
                ('clusXPos', models.FloatField(null=True)),
                ('clusYPos', models.FloatField(null=True)),
                ('teamID', models.FloatField(null=True)),
                ('teamRelX', models.FloatField(null=True)),
                ('teamRelY', models.FloatField(null=True)),
            ],
        ),
    ]
