# Generated by Django 3.0.5 on 2020-04-13 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_auto_20200412_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 17, 57, 44, 584613)),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 17, 57, 44, 584952)),
        ),
    ]
