# Generated by Django 3.0.5 on 2020-04-13 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_auto_20200413_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 20, 44, 47, 122574)),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 20, 44, 47, 122920)),
        ),
    ]
