# Generated by Django 3.0.5 on 2020-04-18 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0010_auto_20200413_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='currLvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 18, 58, 12, 124732)),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 18, 58, 12, 125163)),
        ),
    ]
