# Generated by Django 3.0.5 on 2020-04-20 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0011_auto_20200418_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=100)),
                ('projLvl', models.FloatField(null=True)),
                ('industry', models.CharField(max_length=100)),
                ('projectName', models.CharField(max_length=100)),
                ('sLength', models.FloatField(null=True)),
                ('sWidth', models.FloatField(null=True)),
                ('actualX', models.FloatField(null=True)),
                ('actualY', models.FloatField(null=True)),
                ('angle', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 17, 5, 18, 728270)),
        ),
    ]
