# Generated by Django 3.0.5 on 2020-04-20 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0012_auto_20200420_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 19, 35, 40, 146182)),
        ),
    ]
