# Generated by Django 3.0.5 on 2020-04-20 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0015_auto_20200420_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 21, 11, 57, 882665)),
        ),
        migrations.AlterField(
            model_name='allocpic',
            name='alloc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='allocpic',
            name='savedDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 21, 11, 57, 883426)),
        ),
    ]
