# Generated by Django 3.0.5 on 2020-04-20 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0016_auto_20200420_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocateDT',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 21, 29, 50, 406604)),
        ),
        migrations.AlterField(
            model_name='allocpic',
            name='savedDT',
            field=models.CharField(max_length=100),
        ),
    ]
